SELECT * FROM ACCOUNT A JOIN FOLLOW F ON  A.ID = F.FR_ID JOIN FEED F2 ON  F.FD_ID = F2.ID WHERE A.ID = 'ADMIN';
SELECT * FROM ACCOUNT A JOIN FOLLOW F ON  A.ID = F.FR_ID JOIN FEED F2 ON  F.FD_ID = F2.ID ORDER BY A.ID;

SELECT * FROM FEED;
SELECT * FROM FOLLOW;

SELECT  ROWNUM, F.* FROM (SELECT * FROM FEED WHERE ID IN('user06', 'bomi', 'kimjm') ORDER BY FEED_REGDATE DESC) F WHERE ROWNUM BETWEEN 1 AND 8;

UPDATE FEED SET FEED_REGDATE = SYSDATE WHERE FEED_NO = 19;

INSERT INTO FOLLOW VALUES('user01' , 'kimjm');
INSERT INTO FOLLOW VALUES('user02' , 'kimjm');

SELECT * FROM FOLLOW WHERE FR_ID = 'user01';

SELECT * FROM FOLLOW WHERE FR_ID = 'user02';
