SELECT * FROM ACCOUNT A JOIN FOLLOW F ON  A.ID = F.FR_ID JOIN FEED F2 ON  F.FD_ID = F2.ID WHERE A.ID = 'ADMIN';
SELECT * FROM ACCOUNT A JOIN FOLLOW F ON  A.ID = F.FR_ID JOIN FEED F2 ON  F.FD_ID = F2.ID ORDER BY A.ID;

SELECT * FROM FEED;
SELECT * FROM FOLLOW;
