SELECT * FROM ACCOUNT A JOIN FOLLOW F ON  A.ID = F.FR_ID JOIN FEED F2 ON  F.FD_ID = F2.ID WHERE A.ID = 'ADMIN';
SELECT * FROM ACCOUNT A JOIN FOLLOW F ON  A.ID = F.FR_ID JOIN FEED F2 ON  F.FD_ID = F2.ID ORDER BY A.ID;

SELECT * FROM FEED;
SELECT * FROM FOLLOW;

SELECT  ROWNUM, F.* FROM (SELECT * FROM FEED WHERE ID IN('user06', 'bomi', 'kimjm') ORDER BY FEED_REGDATE DESC) F WHERE ROWNUM BETWEEN 1 AND 8;

UPDATE FEED SET FEED_REGDATE = SYSDATE WHERE FEED_NO = 19;

INSERT INTO FOLLOW VALUES('user01' , 'kimjm');
INSERT INTO FOLLOW VALUES('user02' , 'kimjm');

SELECT * FROM FOLLOW WHERE FR_ID = 'user01';

SELECT * FROM FOLLOW WHERE FR_ID = 'user02';

SELECT * FROM FEED WHERE FEED_NO = 3;
SELECT * FROM COMMENTS;
INSERT INTO COMMENTS VALUES(COM_SEQ.NEXTVAL, 'F', 'user01', '집에가고싶어요,,',SYSDATE, 7);

select * from Likes;
SELECT * FROM FOLLOW;
SELECT * FROM ACCOUNT;
SELECT * FROM PET;
SELECT * FROM FEED WHERE ID = 'user11';
SELECT * FROM COMMENTS;
SELECT * FROM PET WHERE ID = 'user11';
